services:
  backend:
    container_name: flash-me-backend
    build:
      context: ../../ # Points to root of monorepo
      dockerfile: apps/backend/Dockerfile
    network_mode: 'host'
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    environment:
      NODE_ENV: production
      # Database connection parameters to match app.module.ts
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE:-false}
      # Additional parameter for Supabase SSL
      DATABASE_SSL: ${DATABASE_SSL:-true}
      # Set typeorm logging to true for debugging
      TYPEORM_LOGGING: 'true'
      # Force IPv4 DNS resolution
      NODE_OPTIONS: '--dns-result-order=ipv4first'
    network_mode: 'host' # Use host network mode for easier connectivity
    restart: always
    # Add healthcheck to verify container is working properly
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3000/health']
      interval: 10s
      timeout: 5s
      retries: 5
